<?php

namespace Database\Seeders;

use App\Models\Cast;
use App\Models\CastMovie;
use App\Models\Cinema;
use App\Models\CinemaMovie;
use App\Models\FormatMovie;
use App\Models\Movie;
use App\Models\MovieFormatMovie;
use App\Models\MovieGenre;
use App\Models\MovieGenreMovie;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class MovieSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $dataUrlYoutube = [
            'https://www.youtube.com/watch?v=cD9HfSmiJDA',
            'https://www.youtube.com/watch?v=rdtLBPVJ1PM',
            'https://www.youtube.com/watch?v=ZWJaEF8B03I',
            'https://www.youtube.com/watch?v=apMUfr_uqwg',
            'https://www.youtube.com/watch?v=uax3sR17GQQ',
            'https://www.youtube.com/watch?v=HtnWmdup8KQ',
            'https://www.youtube.com/watch?v=j4qlDEzr73I',
            'https://www.youtube.com/watch?v=wHuFuxsQ_Vw',
            'https://www.youtube.com/watch?v=q3GTCsRLzhA',
            'https://www.youtube.com/watch?v=mBqS1Fj_lNo',
            'https://www.youtube.com/watch?v=Bp9s8WNmP20',
            'https://www.youtube.com/watch?v=uyxiITdUsdY',
            'https://www.youtube.com/watch?v=VAbzuIqX9f8',
            'https://www.youtube.com/watch?v=T8YgfQ5hWBc',
            'https://www.youtube.com/watch?v=8Lc04ry_hB0',
            'https://www.youtube.com/watch?v=dNhojMSgS0Y',
            'https://www.youtube.com/watch?v=Hakd3BKnXuo',
            'https://www.youtube.com/watch?v=Vran9iR20_E',
            'https://www.youtube.com/watch?v=0t8FomXzakE',
        ];

        $data_description =
            '<p style="box-sizing: border-box; border: 0px solid #e5e5e5; --tw-translate-x: 0; --tw-translate-y: 0; --tw-rotate: 0; --tw-skew-x: 0; --tw-skew-y: 0; --tw-scale-x: 1; --tw-scale-y: 1; --tw-scroll-snap-strictness: proximity; --tw-ring-offset-width: 0px; --tw-ring-offset-color: #fff; --tw-ring-color: rgba(59,130,246,0.5); --tw-ring-offset-shadow: 0 0 #0000; --tw-ring-shadow: 0 0 #0000; --tw-shadow: 0 0 #0000; --tw-shadow-colored: 0 0 #0000; --header-height: 52px; --header-sticky-mb: 52px; margin: 0px 0px 1em; color: rgba(0, 0, 0, 0.85); font-family: -apple-system, BlinkMacSystemFont, Inter, sans-serif; font-size: 18px; letter-spacing: -0.45px; background-color: #ffffff;"><span style="box-sizing: border-box; border: 0px solid #e5e5e5; --tw-translate-x: 0; --tw-translate-y: 0; --tw-rotate: 0; --tw-skew-x: 0; --tw-skew-y: 0; --tw-scale-x: 1; --tw-scale-y: 1; --tw-scroll-snap-strictness: proximity; --tw-ring-offset-width: 0px; --tw-ring-offset-color: #fff; --tw-ring-color: rgba(59,130,246,0.5); --tw-ring-offset-shadow: 0 0 #0000; --tw-ring-shadow: 0 0 #0000; --tw-shadow: 0 0 #0000; --tw-shadow-colored: 0 0 #0000; --header-height: 52px; --header-sticky-mb: 52px; font-weight: 600;">Kịch bản Bố Gi&agrave;</span>&nbsp;được chắp b&uacute;t bởi ch&iacute;nh&nbsp;<span style="box-sizing: border-box; border: 0px solid #e5e5e5; --tw-translate-x: 0; --tw-translate-y: 0; --tw-rotate: 0; --tw-skew-x: 0; --tw-skew-y: 0; --tw-scale-x: 1; --tw-scale-y: 1; --tw-scroll-snap-strictness: proximity; --tw-ring-offset-width: 0px; --tw-ring-offset-color: #fff; --tw-ring-color: rgba(59,130,246,0.5); --tw-ring-offset-shadow: 0 0 #0000; --tw-ring-shadow: 0 0 #0000; --tw-shadow: 0 0 #0000; --tw-shadow-colored: 0 0 #0000; --header-height: 52px; --header-sticky-mb: 52px; font-weight: 600;">Trấn Th&agrave;nh, đạo diễn bởi Vũ Ngọc Đ&atilde;ng</span>. Phim mang ti&ecirc;u ch&iacute; ho&agrave;n to&agrave;n kh&aacute;c kh&ocirc;ng đặt nặng vấn đề cơm &aacute;o gạo tiền như webdrama trước đ&oacute; m&agrave; tập trung v&agrave;o những c&acirc;u chuyện gia đ&igrave;nh của Ba Sang - Quắn - B&ugrave; Tọt.</p>
            <p style="box-sizing: border-box; border: 0px solid #e5e5e5; --tw-translate-x: 0; --tw-translate-y: 0; --tw-rotate: 0; --tw-skew-x: 0; --tw-skew-y: 0; --tw-scale-x: 1; --tw-scale-y: 1; --tw-scroll-snap-strictness: proximity; --tw-ring-offset-width: 0px; --tw-ring-offset-color: #fff; --tw-ring-color: rgba(59,130,246,0.5); --tw-ring-offset-shadow: 0 0 #0000; --tw-ring-shadow: 0 0 #0000; --tw-shadow: 0 0 #0000; --tw-shadow-colored: 0 0 #0000; --header-height: 52px; --header-sticky-mb: 52px; margin: 0px 0px 1em; color: rgba(0, 0, 0, 0.85); font-family: -apple-system, BlinkMacSystemFont, Inter, sans-serif; font-size: 18px; letter-spacing: -0.45px; background-color: #ffffff; text-align: center;"><span class="block cursor-pointer " style="box-sizing: border-box; border: 0px solid #e5e5e5; --tw-translate-x: 0; --tw-translate-y: 0; --tw-rotate: 0; --tw-skew-x: 0; --tw-skew-y: 0; --tw-scale-x: 1; --tw-scale-y: 1; --tw-scroll-snap-strictness: proximity; --tw-ring-offset-width: 0px; --tw-ring-offset-color: #fff; --tw-ring-color: rgba(59,130,246,0.5); --tw-ring-offset-shadow: 0 0 #0000; --tw-ring-shadow: 0 0 #0000; --tw-shadow: 0 0 #0000; --tw-shadow-colored: 0 0 #0000; --header-height: 52px; --header-sticky-mb: 52px; display: block; cursor: pointer;"><img class="mx-auto mt-8 mb-2" style="box-sizing: border-box; border: 0px solid #e5e5e5; --tw-translate-x: 0; --tw-translate-y: 0; --tw-rotate: 0; --tw-skew-x: 0; --tw-skew-y: 0; --tw-scale-x: 1; --tw-scale-y: 1; --tw-scroll-snap-strictness: proximity; --tw-ring-offset-width: 0px; --tw-ring-offset-color: #fff; --tw-ring-color: rgba(59,130,246,0.5); --tw-ring-offset-shadow: 0 0 #0000; --tw-ring-shadow: 0 0 #0000; --tw-shadow: 0 0 #0000; --tw-shadow-colored: 0 0 #0000; --header-height: 52px; --header-sticky-mb: 52px; display: block; vertical-align: middle; max-width: 100%; height: auto !important; margin: 0px auto;" src="https://static.mservice.io/blogscontents/momo-upload-api-210312150001-637511580015634364.jpg" loading="lazy" /></span><em style="box-sizing: border-box; border: 0px solid #e5e5e5; --tw-translate-x: 0; --tw-translate-y: 0; --tw-rotate: 0; --tw-skew-x: 0; --tw-skew-y: 0; --tw-scale-x: 1; --tw-scale-y: 1; --tw-scroll-snap-strictness: proximity; --tw-ring-offset-width: 0px; --tw-ring-offset-color: #fff; --tw-ring-color: rgba(59,130,246,0.5); --tw-ring-offset-shadow: 0 0 #0000; --tw-ring-shadow: 0 0 #0000; --tw-shadow: 0 0 #0000; --tw-shadow-colored: 0 0 #0000; --header-height: 52px; --header-sticky-mb: 52px;">Poster ch&iacute;nh thức của Bố Gi&agrave;</em></p>
            <h2 id="mau-sac-hinh-anh" class="ckemm_title_spy" style="box-sizing: border-box; border: 0px solid #e5e5e5; --tw-translate-x: 0; --tw-translate-y: 0; --tw-rotate: 0; --tw-skew-x: 0; --tw-skew-y: 0; --tw-scale-x: 1; --tw-scale-y: 1; --tw-scroll-snap-strictness: proximity; --tw-ring-offset-width: 0px; --tw-ring-offset-color: #fff; --tw-ring-color: rgba(59,130,246,0.5); --tw-ring-offset-shadow: 0 0 #0000; --tw-ring-shadow: 0 0 #0000; --tw-shadow: 0 0 #0000; --tw-shadow-colored: 0 0 #0000; --header-height: 52px; --header-sticky-mb: 52px; font-size: 1.75rem; margin: 3rem 0px 1rem; scroll-margin-top: 90px; overflow-wrap: break-word; line-height: 2rem; color: rgba(0, 0, 0, 0.85); font-family: -apple-system, BlinkMacSystemFont, Inter, sans-serif; letter-spacing: -0.45px; background-color: #ffffff;">M&agrave;u sắc v&agrave; h&igrave;nh ảnh</h2>
            <p style="box-sizing: border-box; border: 0px solid #e5e5e5; --tw-translate-x: 0; --tw-translate-y: 0; --tw-rotate: 0; --tw-skew-x: 0; --tw-skew-y: 0; --tw-scale-x: 1; --tw-scale-y: 1; --tw-scroll-snap-strictness: proximity; --tw-ring-offset-width: 0px; --tw-ring-offset-color: #fff; --tw-ring-color: rgba(59,130,246,0.5); --tw-ring-offset-shadow: 0 0 #0000; --tw-ring-shadow: 0 0 #0000; --tw-shadow: 0 0 #0000; --tw-shadow-colored: 0 0 #0000; --header-height: 52px; --header-sticky-mb: 52px; margin: 0px 0px 1em; color: rgba(0, 0, 0, 0.85); font-family: -apple-system, BlinkMacSystemFont, Inter, sans-serif; font-size: 18px; letter-spacing: -0.45px; background-color: #ffffff;">Nhẹ nh&agrave;ng v&agrave; ấm &aacute;p đ&oacute; l&agrave; những cảm quan m&agrave; Bố Gi&agrave; đem lại cho người xem xuy&ecirc;n suốt bộ phim. B&ecirc;n cạnh đ&oacute; x&oacute;m ngh&egrave;o quanh năm ngập nước c&ugrave;ng m&oacute;n cơm sườn cũng l&agrave; đặc trưng của S&agrave;i G&ograve;n thu nhỏ, những c&aacute;nh cửa cũ m&egrave;m c&ugrave;ng h&agrave;ng x&oacute;m lu&ocirc;n lu&ocirc;n ngồi trước cửa l&agrave; điểm nhấn kh&oacute; phai mỗi khi bước v&agrave;o con hẻm n&agrave;o đ&oacute;.&nbsp;&nbsp;</p>
            <p style="box-sizing: border-box; border: 0px solid #e5e5e5; --tw-translate-x: 0; --tw-translate-y: 0; --tw-rotate: 0; --tw-skew-x: 0; --tw-skew-y: 0; --tw-scale-x: 1; --tw-scale-y: 1; --tw-scroll-snap-strictness: proximity; --tw-ring-offset-width: 0px; --tw-ring-offset-color: #fff; --tw-ring-color: rgba(59,130,246,0.5); --tw-ring-offset-shadow: 0 0 #0000; --tw-ring-shadow: 0 0 #0000; --tw-shadow: 0 0 #0000; --tw-shadow-colored: 0 0 #0000; --header-height: 52px; --header-sticky-mb: 52px; margin: 0px 0px 1em; color: rgba(0, 0, 0, 0.85); font-family: -apple-system, BlinkMacSystemFont, Inter, sans-serif; font-size: 18px; letter-spacing: -0.45px; background-color: #ffffff; text-align: center;"><span class="block cursor-pointer " style="box-sizing: border-box; border: 0px solid #e5e5e5; --tw-translate-x: 0; --tw-translate-y: 0; --tw-rotate: 0; --tw-skew-x: 0; --tw-skew-y: 0; --tw-scale-x: 1; --tw-scale-y: 1; --tw-scroll-snap-strictness: proximity; --tw-ring-offset-width: 0px; --tw-ring-offset-color: #fff; --tw-ring-color: rgba(59,130,246,0.5); --tw-ring-offset-shadow: 0 0 #0000; --tw-ring-shadow: 0 0 #0000; --tw-shadow: 0 0 #0000; --tw-shadow-colored: 0 0 #0000; --header-height: 52px; --header-sticky-mb: 52px; display: block; cursor: pointer;"><img class="mx-auto mt-8 mb-2" style="box-sizing: border-box; border: 0px solid #e5e5e5; --tw-translate-x: 0; --tw-translate-y: 0; --tw-rotate: 0; --tw-skew-x: 0; --tw-skew-y: 0; --tw-scale-x: 1; --tw-scale-y: 1; --tw-scroll-snap-strictness: proximity; --tw-ring-offset-width: 0px; --tw-ring-offset-color: #fff; --tw-ring-color: rgba(59,130,246,0.5); --tw-ring-offset-shadow: 0 0 #0000; --tw-ring-shadow: 0 0 #0000; --tw-shadow: 0 0 #0000; --tw-shadow-colored: 0 0 #0000; --header-height: 52px; --header-sticky-mb: 52px; display: block; vertical-align: middle; max-width: 100%; height: auto !important; margin: 0px auto;" src="https://static.mservice.io/blogscontents/momo-upload-api-210312150036-637511580365322410.jpg" loading="lazy" /></span><em style="box-sizing: border-box; border: 0px solid #e5e5e5; --tw-translate-x: 0; --tw-translate-y: 0; --tw-rotate: 0; --tw-skew-x: 0; --tw-skew-y: 0; --tw-scale-x: 1; --tw-scale-y: 1; --tw-scroll-snap-strictness: proximity; --tw-ring-offset-width: 0px; --tw-ring-offset-color: #fff; --tw-ring-color: rgba(59,130,246,0.5); --tw-ring-offset-shadow: 0 0 #0000; --tw-ring-shadow: 0 0 #0000; --tw-shadow: 0 0 #0000; --tw-shadow-colored: 0 0 #0000; --header-height: 52px; --header-sticky-mb: 52px;">Ba Sang trong Bố Gi&agrave; với t&ocirc;ng m&agrave;u ấm n&oacute;ng.</em></p>
            <p style="box-sizing: border-box; border: 0px solid #e5e5e5; --tw-translate-x: 0; --tw-translate-y: 0; --tw-rotate: 0; --tw-skew-x: 0; --tw-skew-y: 0; --tw-scale-x: 1; --tw-scale-y: 1; --tw-scroll-snap-strictness: proximity; --tw-ring-offset-width: 0px; --tw-ring-offset-color: #fff; --tw-ring-color: rgba(59,130,246,0.5); --tw-ring-offset-shadow: 0 0 #0000; --tw-ring-shadow: 0 0 #0000; --tw-shadow: 0 0 #0000; --tw-shadow-colored: 0 0 #0000; --header-height: 52px; --header-sticky-mb: 52px; margin: 0px 0px 1em; color: rgba(0, 0, 0, 0.85); font-family: -apple-system, BlinkMacSystemFont, Inter, sans-serif; font-size: 18px; letter-spacing: -0.45px; background-color: #ffffff;">Việc khắc hoạ một gia đ&igrave;nh đậm chất S&agrave;i G&ograve;n c&ograve;n ở c&aacute;ch xưng h&ocirc; v&agrave; n&oacute;i chuyện với nhau, &ldquo;ba&rdquo; - &ldquo;tui&rdquo; c&oacute; lẽ l&agrave; hai từ th&acirc;n thương nhất m&agrave; mỗi người con miền Nam khi nghe thấy đều nhớ về gia đ&igrave;nh m&igrave;nh. Ngo&agrave;i ra do c&oacute; b&agrave;n tay của đạo diễn Vũ Ngọc Đ&atilde;ng n&ecirc;n những c&uacute; m&aacute;y của phim dường như ch&iacute;nh đ&ocirc;i mắt của ch&uacute;ng ta đang quan s&aacute;t gia đ&igrave;nh nhỏ của Ba Sang. Ấn tượng nhất c&oacute; lẽ l&agrave; những c&uacute; m&aacute;y oneshot d&agrave;i 5-7 ph&uacute;t m&agrave; &iacute;t ai nhận ra, quả thực những c&uacute; m&aacute;y n&agrave;y nếu để &yacute; r&otilde; bạn sẽ thấy được sự ăn &yacute; cũng như kh&eacute;o l&eacute;o của to&agrave;n bộ diễn vi&ecirc;n v&agrave; cameraman.</p>
            <p class="embed-responsive embed-responsive-16by9" style="box-sizing: border-box; border: 0px solid #e5e5e5; --tw-translate-x: 0; --tw-translate-y: 0; --tw-rotate: 0; --tw-skew-x: 0; --tw-skew-y: 0; --tw-scale-x: 1; --tw-scale-y: 1; --tw-scroll-snap-strictness: proximity; --tw-ring-offset-width: 0px; --tw-ring-offset-color: #fff; --tw-ring-color: rgba(59,130,246,0.5); --tw-ring-offset-shadow: 0 0 #0000; --tw-ring-shadow: 0 0 #0000; --tw-shadow: 0 0 #0000; --tw-shadow-colored: 0 0 #0000; --header-height: 52px; --header-sticky-mb: 52px; margin: 0px 0px 1em; position: relative; width: 744px; padding: 0px; overflow: hidden; color: rgba(0, 0, 0, 0.85); font-family: -apple-system, BlinkMacSystemFont, Inter, sans-serif; font-size: 18px; letter-spacing: -0.45px; background-color: #ffffff;"><iframe id="912589160" style="box-sizing: border-box; border-width: 0px; border-style: initial; --tw-translate-x: 0; --tw-translate-y: 0; --tw-rotate: 0; --tw-skew-x: 0; --tw-skew-y: 0; --tw-scale-x: 1; --tw-scale-y: 1; --tw-scroll-snap-strictness: proximity; --tw-ring-offset-width: 0px; --tw-ring-offset-color: #fff; --tw-ring-color: rgba(59,130,246,0.5); --tw-ring-offset-shadow: 0 0 #0000; --tw-ring-shadow: 0 0 #0000; --tw-shadow: 0 0 #0000; --tw-shadow-colored: 0 0 #0000; --header-height: 52px; --header-sticky-mb: 52px; display: block; vertical-align: middle; position: absolute; top: 0px; bottom: 0px; left: 0px; width: 744px; height: 418.5px;" src="https://www.youtube.com/embed/jluSu8Rw6YE?autoplay=0&amp;rel=0&amp;enablejsapi=1&amp;origin=https%3A%2F%2Fmomo.vn" allowfullscreen="" data-gtm-yt-inspected-10104547_111="true" data-gtm-yt-inspected-1_19="true"></iframe></p>
            <h2 id="kich-ban-bo-gia" class="ckemm_title_spy" style="box-sizing: border-box; border: 0px solid #e5e5e5; --tw-translate-x: 0; --tw-translate-y: 0; --tw-rotate: 0; --tw-skew-x: 0; --tw-skew-y: 0; --tw-scale-x: 1; --tw-scale-y: 1; --tw-scroll-snap-strictness: proximity; --tw-ring-offset-width: 0px; --tw-ring-offset-color: #fff; --tw-ring-color: rgba(59,130,246,0.5); --tw-ring-offset-shadow: 0 0 #0000; --tw-ring-shadow: 0 0 #0000; --tw-shadow: 0 0 #0000; --tw-shadow-colored: 0 0 #0000; --header-height: 52px; --header-sticky-mb: 52px; font-size: 1.75rem; margin: 3rem 0px 1rem; scroll-margin-top: 90px; overflow-wrap: break-word; line-height: 2rem; color: rgba(0, 0, 0, 0.85); font-family: -apple-system, BlinkMacSystemFont, Inter, sans-serif; letter-spacing: -0.45px; background-color: #ffffff;">Kịch bản</h2>
            <p style="box-sizing: border-box; border: 0px solid #e5e5e5; --tw-translate-x: 0; --tw-translate-y: 0; --tw-rotate: 0; --tw-skew-x: 0; --tw-skew-y: 0; --tw-scale-x: 1; --tw-scale-y: 1; --tw-scroll-snap-strictness: proximity; --tw-ring-offset-width: 0px; --tw-ring-offset-color: #fff; --tw-ring-color: rgba(59,130,246,0.5); --tw-ring-offset-shadow: 0 0 #0000; --tw-ring-shadow: 0 0 #0000; --tw-shadow: 0 0 #0000; --tw-shadow-colored: 0 0 #0000; --header-height: 52px; --header-sticky-mb: 52px; margin: 0px 0px 1em; color: rgba(0, 0, 0, 0.85); font-family: -apple-system, BlinkMacSystemFont, Inter, sans-serif; font-size: 18px; letter-spacing: -0.45px; background-color: #ffffff;">Vốn dĩ xuất ph&aacute;t điểm từ webdrama, nhưng Trấn Th&agrave;nh vẫn kh&eacute;o l&eacute;o để bộ phim c&oacute; nhiều t&iacute;nh chất điện ảnh nhất c&oacute; thể. Nhưng việc tạo t&igrave;nh tiết để ph&aacute;t triển bộ phim lại v&ocirc; t&igrave;nh mang đến một mạch phim c&oacute; qu&aacute; nhiều n&uacute;t thắt m&agrave; kịch bản kh&ocirc;ng thể giải quyết thỏa m&atilde;n cho người xem.&nbsp;</p>
            <p style="box-sizing: border-box; border: 0px solid #e5e5e5; --tw-translate-x: 0; --tw-translate-y: 0; --tw-rotate: 0; --tw-skew-x: 0; --tw-skew-y: 0; --tw-scale-x: 1; --tw-scale-y: 1; --tw-scroll-snap-strictness: proximity; --tw-ring-offset-width: 0px; --tw-ring-offset-color: #fff; --tw-ring-color: rgba(59,130,246,0.5); --tw-ring-offset-shadow: 0 0 #0000; --tw-ring-shadow: 0 0 #0000; --tw-shadow: 0 0 #0000; --tw-shadow-colored: 0 0 #0000; --header-height: 52px; --header-sticky-mb: 52px; margin: 0px 0px 1em; color: rgba(0, 0, 0, 0.85); font-family: -apple-system, BlinkMacSystemFont, Inter, sans-serif; font-size: 18px; letter-spacing: -0.45px; background-color: #ffffff; text-align: center;"><span class="block cursor-pointer " style="box-sizing: border-box; border: 0px solid #e5e5e5; --tw-translate-x: 0; --tw-translate-y: 0; --tw-rotate: 0; --tw-skew-x: 0; --tw-skew-y: 0; --tw-scale-x: 1; --tw-scale-y: 1; --tw-scroll-snap-strictness: proximity; --tw-ring-offset-width: 0px; --tw-ring-offset-color: #fff; --tw-ring-color: rgba(59,130,246,0.5); --tw-ring-offset-shadow: 0 0 #0000; --tw-ring-shadow: 0 0 #0000; --tw-shadow: 0 0 #0000; --tw-shadow-colored: 0 0 #0000; --header-height: 52px; --header-sticky-mb: 52px; display: block; cursor: pointer;"><img class="mx-auto mt-8 mb-2" style="box-sizing: border-box; border: 0px solid #e5e5e5; --tw-translate-x: 0; --tw-translate-y: 0; --tw-rotate: 0; --tw-skew-x: 0; --tw-skew-y: 0; --tw-scale-x: 1; --tw-scale-y: 1; --tw-scroll-snap-strictness: proximity; --tw-ring-offset-width: 0px; --tw-ring-offset-color: #fff; --tw-ring-color: rgba(59,130,246,0.5); --tw-ring-offset-shadow: 0 0 #0000; --tw-ring-shadow: 0 0 #0000; --tw-shadow: 0 0 #0000; --tw-shadow-colored: 0 0 #0000; --header-height: 52px; --header-sticky-mb: 52px; display: block; vertical-align: middle; max-width: 100%; height: auto !important; margin: 0px auto;" src="https://static.mservice.io/blogscontents/momo-upload-api-210312150112-637511580722344624.jpg" loading="lazy" /></span><em style="box-sizing: border-box; border: 0px solid #e5e5e5; --tw-translate-x: 0; --tw-translate-y: 0; --tw-rotate: 0; --tw-skew-x: 0; --tw-skew-y: 0; --tw-scale-x: 1; --tw-scale-y: 1; --tw-scroll-snap-strictness: proximity; --tw-ring-offset-width: 0px; --tw-ring-offset-color: #fff; --tw-ring-color: rgba(59,130,246,0.5); --tw-ring-offset-shadow: 0 0 #0000; --tw-ring-shadow: 0 0 #0000; --tw-shadow: 0 0 #0000; --tw-shadow-colored: 0 0 #0000; --header-height: 52px; --header-sticky-mb: 52px;">Nh&igrave;n vậy chứ kh&oacute; chịu lắm &agrave;</em></p>
            <p style="box-sizing: border-box; border: 0px solid #e5e5e5; --tw-translate-x: 0; --tw-translate-y: 0; --tw-rotate: 0; --tw-skew-x: 0; --tw-skew-y: 0; --tw-scale-x: 1; --tw-scale-y: 1; --tw-scroll-snap-strictness: proximity; --tw-ring-offset-width: 0px; --tw-ring-offset-color: #fff; --tw-ring-color: rgba(59,130,246,0.5); --tw-ring-offset-shadow: 0 0 #0000; --tw-ring-shadow: 0 0 #0000; --tw-shadow: 0 0 #0000; --tw-shadow-colored: 0 0 #0000; --header-height: 52px; --header-sticky-mb: 52px; margin: 0px 0px 1em; color: rgba(0, 0, 0, 0.85); font-family: -apple-system, BlinkMacSystemFont, Inter, sans-serif; font-size: 18px; letter-spacing: -0.45px; background-color: #ffffff;">Mở đầu phim rất nhẹ nh&agrave;ng, c&aacute;c nh&acirc;n vật ch&iacute;nh l&agrave;m c&ocirc;ng việc của m&igrave;nh cảm gi&aacute;c y&ecirc;n b&igrave;nh ngự trị trong khu x&oacute;m ngh&egrave;o ngập nước. Dần dần c&aacute;c nh&acirc;n vật c&oacute; đ&oacute;ng g&oacute;p th&ecirc;m v&agrave;o c&acirc;u chuyện dần được giới thiệu. Đ&acirc;y l&agrave; một cấu tr&uacute;c cơ bản của mọi bộ phim v&agrave; Bố Gi&agrave; l&agrave;m tốt điều n&agrave;y, nhưng khi đ&atilde; đi được đến giữa phim th&igrave; c&acirc;u chuyện bẻ l&aacute;i sang hướng kh&aacute;c. Những drama được nối tiếp th&ecirc;m v&agrave;o, đẩy nhịp phim l&ecirc;n cao khi những m&acirc;u thuẫn giữa Ba Sang v&agrave; Quắn ng&agrave;y c&agrave;ng lớn, phim qu&aacute; tập trung v&agrave;o việc thể hiện c&aacute; t&iacute;nh của hai người m&agrave; qu&ecirc;n mất bồi đắp những nh&acirc;n vật phụ, ở đ&acirc;y c&oacute; thể nhắc đến đ&oacute; l&agrave; B&ugrave; Tọt - nh&acirc;n vật sẽ nối hai cha con nh&agrave; Ba Sang lại.&nbsp;</p>
            <div class="text-center" style="box-sizing: border-box; border: 0px solid #e5e5e5; --tw-translate-x: 0; --tw-translate-y: 0; --tw-rotate: 0; --tw-skew-x: 0; --tw-skew-y: 0; --tw-scale-x: 1; --tw-scale-y: 1; --tw-scroll-snap-strictness: proximity; --tw-ring-offset-width: 0px; --tw-ring-offset-color: #fff; --tw-ring-color: rgba(59,130,246,0.5); --tw-ring-offset-shadow: 0 0 #0000; --tw-ring-shadow: 0 0 #0000; --tw-shadow: 0 0 #0000; --tw-shadow-colored: 0 0 #0000; --header-height: 52px; --header-sticky-mb: 52px; text-align: center; color: rgba(0, 0, 0, 0.85); font-family: -apple-system, BlinkMacSystemFont, Inter, sans-serif; font-size: 18px; letter-spacing: -0.45px; background-color: #ffffff;">
            <p style="box-sizing: border-box; border: 0px solid #e5e5e5; --tw-translate-x: 0; --tw-translate-y: 0; --tw-rotate: 0; --tw-skew-x: 0; --tw-skew-y: 0; --tw-scale-x: 1; --tw-scale-y: 1; --tw-scroll-snap-strictness: proximity; --tw-ring-offset-width: 0px; --tw-ring-offset-color: #fff; --tw-ring-color: rgba(59,130,246,0.5); --tw-ring-offset-shadow: 0 0 #0000; --tw-ring-shadow: 0 0 #0000; --tw-shadow: 0 0 #0000; --tw-shadow-colored: 0 0 #0000; --header-height: 52px; --header-sticky-mb: 52px; margin: 0px;"><a class="btn btn-primary-2 btn-pulse" style="box-sizing: border-box; border: 0px solid #e5e5e5; --tw-translate-x: 0; --tw-translate-y: 0; --tw-rotate: 0; --tw-skew-x: 0; --tw-skew-y: 0; --tw-scale-x: 1; --tw-scale-y: 1; --tw-scroll-snap-strictness: proximity; --tw-ring-offset-width: 0px; --tw-ring-offset-color: #fff; --tw-ring-color: rgba(59,130,246,0.5); --tw-ring-offset-shadow: 0 0 #0000; --tw-ring-shadow: 0 0 #0000; --tw-shadow: 0 0 #0000; --tw-shadow-colored: 0 0 #0000; --header-height: 52px; --header-sticky-mb: 52px; text-decoration: inherit; display: inline-block; border-radius: 0.375rem; --tw-bg-opacity: 1; background-color: rgb(190 24 93/var(--tw-bg-opacity)); padding: 0.5rem 1rem; font-size: 0.875rem; line-height: 1.25rem; font-weight: bold; --tw-text-opacity: 0.9; transition-property: all; transition-timing-function: cubic-bezier(0.4, 0, 0.2, 1); transition-duration: 0.15s;" href="https://bit.ly/MoMo-BoGia" target="_blank" rel="noopener">ĐẶT V&Eacute; BỐ GI&Agrave; NGAY</a></p>
            </div>
            <p style="box-sizing: border-box; border: 0px solid #e5e5e5; --tw-translate-x: 0; --tw-translate-y: 0; --tw-rotate: 0; --tw-skew-x: 0; --tw-skew-y: 0; --tw-scale-x: 1; --tw-scale-y: 1; --tw-scroll-snap-strictness: proximity; --tw-ring-offset-width: 0px; --tw-ring-offset-color: #fff; --tw-ring-color: rgba(59,130,246,0.5); --tw-ring-offset-shadow: 0 0 #0000; --tw-ring-shadow: 0 0 #0000; --tw-shadow: 0 0 #0000; --tw-shadow-colored: 0 0 #0000; --header-height: 52px; --header-sticky-mb: 52px; margin: 0px 0px 1em; color: rgba(0, 0, 0, 0.85); font-family: -apple-system, BlinkMacSystemFont, Inter, sans-serif; font-size: 18px; letter-spacing: -0.45px; background-color: #ffffff; text-align: center;"><span class="block cursor-pointer " style="box-sizing: border-box; border: 0px solid #e5e5e5; --tw-translate-x: 0; --tw-translate-y: 0; --tw-rotate: 0; --tw-skew-x: 0; --tw-skew-y: 0; --tw-scale-x: 1; --tw-scale-y: 1; --tw-scroll-snap-strictness: proximity; --tw-ring-offset-width: 0px; --tw-ring-offset-color: #fff; --tw-ring-color: rgba(59,130,246,0.5); --tw-ring-offset-shadow: 0 0 #0000; --tw-ring-shadow: 0 0 #0000; --tw-shadow: 0 0 #0000; --tw-shadow-colored: 0 0 #0000; --header-height: 52px; --header-sticky-mb: 52px; display: block; cursor: pointer;"><img class="mx-auto mt-8 mb-2" style="box-sizing: border-box; border: 0px solid #e5e5e5; --tw-translate-x: 0; --tw-translate-y: 0; --tw-rotate: 0; --tw-skew-x: 0; --tw-skew-y: 0; --tw-scale-x: 1; --tw-scale-y: 1; --tw-scroll-snap-strictness: proximity; --tw-ring-offset-width: 0px; --tw-ring-offset-color: #fff; --tw-ring-color: rgba(59,130,246,0.5); --tw-ring-offset-shadow: 0 0 #0000; --tw-ring-shadow: 0 0 #0000; --tw-shadow: 0 0 #0000; --tw-shadow-colored: 0 0 #0000; --header-height: 52px; --header-sticky-mb: 52px; display: block; vertical-align: middle; max-width: 100%; height: auto !important; margin: 0px auto;" src="https://static.mservice.io/blogscontents/momo-upload-api-210312150128-637511580885772559.jpg" loading="lazy" /></span><em style="box-sizing: border-box; border: 0px solid #e5e5e5; --tw-translate-x: 0; --tw-translate-y: 0; --tw-rotate: 0; --tw-skew-x: 0; --tw-skew-y: 0; --tw-scale-x: 1; --tw-scale-y: 1; --tw-scroll-snap-strictness: proximity; --tw-ring-offset-width: 0px; --tw-ring-offset-color: #fff; --tw-ring-color: rgba(59,130,246,0.5); --tw-ring-offset-shadow: 0 0 #0000; --tw-ring-shadow: 0 0 #0000; --tw-shadow: 0 0 #0000; --tw-shadow-colored: 0 0 #0000; --header-height: 52px; --header-sticky-mb: 52px;">Sự y&ecirc;u thương chăm lo v&ocirc; vờ của Ba Sang</em></p>
            <p style="box-sizing: border-box; border: 0px solid #e5e5e5; --tw-translate-x: 0; --tw-translate-y: 0; --tw-rotate: 0; --tw-skew-x: 0; --tw-skew-y: 0; --tw-scale-x: 1; --tw-scale-y: 1; --tw-scroll-snap-strictness: proximity; --tw-ring-offset-width: 0px; --tw-ring-offset-color: #fff; --tw-ring-color: rgba(59,130,246,0.5); --tw-ring-offset-shadow: 0 0 #0000; --tw-ring-shadow: 0 0 #0000; --tw-shadow: 0 0 #0000; --tw-shadow-colored: 0 0 #0000; --header-height: 52px; --header-sticky-mb: 52px; margin: 0px 0px 1em; color: rgba(0, 0, 0, 0.85); font-family: -apple-system, BlinkMacSystemFont, Inter, sans-serif; font-size: 18px; letter-spacing: -0.45px; background-color: #ffffff;">Tiếp đ&oacute; l&agrave; nh&acirc;n vật của L&ecirc; Giang bị bỏ ngỏ, c&oacute; lẽ đ&acirc;y l&agrave; nh&acirc;n vật g&acirc;y nuối tiếc nhất của phim Bố Gi&agrave; v&igrave; đến cuối phim c&ocirc; đi về đ&acirc;u hay như thế n&agrave;o l&agrave; một ẩn số. Đồng h&agrave;nh sự biến mất của L&ecirc; Giang đ&oacute; l&agrave; người y&ecirc;u của Quắn, sau khi đồng cam cộng khổ c&ugrave;ng Quắn c&ocirc; cũng mất dạng chỉ để lại những gi&acirc;y ph&uacute;t n&oacute;ng bỏng ở đầu phim.</p>
            <p style="box-sizing: border-box; border: 0px solid #e5e5e5; --tw-translate-x: 0; --tw-translate-y: 0; --tw-rotate: 0; --tw-skew-x: 0; --tw-skew-y: 0; --tw-scale-x: 1; --tw-scale-y: 1; --tw-scroll-snap-strictness: proximity; --tw-ring-offset-width: 0px; --tw-ring-offset-color: #fff; --tw-ring-color: rgba(59,130,246,0.5); --tw-ring-offset-shadow: 0 0 #0000; --tw-ring-shadow: 0 0 #0000; --tw-shadow: 0 0 #0000; --tw-shadow-colored: 0 0 #0000; --header-height: 52px; --header-sticky-mb: 52px; margin: 0px 0px 1em; color: rgba(0, 0, 0, 0.85); font-family: -apple-system, BlinkMacSystemFont, Inter, sans-serif; font-size: 18px; letter-spacing: -0.45px; background-color: #ffffff; text-align: center;"><span class="block cursor-pointer " style="box-sizing: border-box; border: 0px solid #e5e5e5; --tw-translate-x: 0; --tw-translate-y: 0; --tw-rotate: 0; --tw-skew-x: 0; --tw-skew-y: 0; --tw-scale-x: 1; --tw-scale-y: 1; --tw-scroll-snap-strictness: proximity; --tw-ring-offset-width: 0px; --tw-ring-offset-color: #fff; --tw-ring-color: rgba(59,130,246,0.5); --tw-ring-offset-shadow: 0 0 #0000; --tw-ring-shadow: 0 0 #0000; --tw-shadow: 0 0 #0000; --tw-shadow-colored: 0 0 #0000; --header-height: 52px; --header-sticky-mb: 52px; display: block; cursor: pointer;"><img class="mx-auto mt-8 mb-2" style="box-sizing: border-box; border: 0px solid #e5e5e5; --tw-translate-x: 0; --tw-translate-y: 0; --tw-rotate: 0; --tw-skew-x: 0; --tw-skew-y: 0; --tw-scale-x: 1; --tw-scale-y: 1; --tw-scroll-snap-strictness: proximity; --tw-ring-offset-width: 0px; --tw-ring-offset-color: #fff; --tw-ring-color: rgba(59,130,246,0.5); --tw-ring-offset-shadow: 0 0 #0000; --tw-ring-shadow: 0 0 #0000; --tw-shadow: 0 0 #0000; --tw-shadow-colored: 0 0 #0000; --header-height: 52px; --header-sticky-mb: 52px; display: block; vertical-align: middle; max-width: 100%; height: auto !important; margin: 0px auto;" src="https://static.mservice.io/blogscontents/momo-upload-api-210312150207-637511581270279352.jpg" loading="lazy" /></span><em style="box-sizing: border-box; border: 0px solid #e5e5e5; --tw-translate-x: 0; --tw-translate-y: 0; --tw-rotate: 0; --tw-skew-x: 0; --tw-skew-y: 0; --tw-scale-x: 1; --tw-scale-y: 1; --tw-scroll-snap-strictness: proximity; --tw-ring-offset-width: 0px; --tw-ring-offset-color: #fff; --tw-ring-color: rgba(59,130,246,0.5); --tw-ring-offset-shadow: 0 0 #0000; --tw-ring-shadow: 0 0 #0000; --tw-shadow: 0 0 #0000; --tw-shadow-colored: 0 0 #0000; --header-height: 52px; --header-sticky-mb: 52px;">Cameo xịn từ vị tr&iacute; của Quang Trung</em></p>
            <p style="box-sizing: border-box; border: 0px solid #e5e5e5; --tw-translate-x: 0; --tw-translate-y: 0; --tw-rotate: 0; --tw-skew-x: 0; --tw-skew-y: 0; --tw-scale-x: 1; --tw-scale-y: 1; --tw-scroll-snap-strictness: proximity; --tw-ring-offset-width: 0px; --tw-ring-offset-color: #fff; --tw-ring-color: rgba(59,130,246,0.5); --tw-ring-offset-shadow: 0 0 #0000; --tw-ring-shadow: 0 0 #0000; --tw-shadow: 0 0 #0000; --tw-shadow-colored: 0 0 #0000; --header-height: 52px; --header-sticky-mb: 52px; margin: 0px 0px 1em; color: rgba(0, 0, 0, 0.85); font-family: -apple-system, BlinkMacSystemFont, Inter, sans-serif; font-size: 18px; letter-spacing: -0.45px; background-color: #ffffff;">C&aacute;i kết h&agrave;i l&ograve;ng nhất trong tất cả nh&acirc;n vật c&oacute; lẽ l&agrave; Qu&yacute;. Ở đ&acirc;y kh&ocirc;ng phải l&agrave; c&aacute;i kết hả dạ, m&agrave; l&agrave; c&aacute;i kết đại diện cho sự nh&acirc;n quả, Qu&yacute; ho&agrave;n lương nhưng c&aacute;i gi&aacute; phải trả l&agrave; kh&aacute; đắt, nhắc nhở mỗi ch&uacute;ng ta về một kiếp người. Vừa giận Qu&yacute; nhưng cũng rất thương Qu&yacute; v&agrave; cảnh Qu&yacute; ng&atilde; xuống c&oacute; lẽ l&agrave; một trong những cảnh mang lại nhiều cảm x&uacute;c cho người xem nhất.</p>
            <p style="box-sizing: border-box; border: 0px solid #e5e5e5; --tw-translate-x: 0; --tw-translate-y: 0; --tw-rotate: 0; --tw-skew-x: 0; --tw-skew-y: 0; --tw-scale-x: 1; --tw-scale-y: 1; --tw-scroll-snap-strictness: proximity; --tw-ring-offset-width: 0px; --tw-ring-offset-color: #fff; --tw-ring-color: rgba(59,130,246,0.5); --tw-ring-offset-shadow: 0 0 #0000; --tw-ring-shadow: 0 0 #0000; --tw-shadow: 0 0 #0000; --tw-shadow-colored: 0 0 #0000; --header-height: 52px; --header-sticky-mb: 52px; margin: 0px 0px 1em; color: rgba(0, 0, 0, 0.85); font-family: -apple-system, BlinkMacSystemFont, Inter, sans-serif; font-size: 18px; letter-spacing: -0.45px; background-color: #ffffff;">Điểm cuối c&ugrave;ng ở kịch bản đ&oacute; l&agrave; ph&acirc;n cảnh Ba Sang v&agrave; Quắn v&agrave;o ph&ograve;ng mổ. C&oacute; lẽ kịch bản muốn x&acirc;y dựng đ&acirc;y l&agrave; cảnh sẽ +1 sức mạnh, +1 niềm tin v&agrave; +1 sự vui vẻ nhưng c&aacute; nh&acirc;n m&igrave;nh thấy đ&acirc;y l&agrave; t&igrave;nh tiết ph&aacute; vỡ sự liền mạch của phim. Nếu thay v&agrave;o đ&oacute; l&agrave; một cảnh cinematic (điện ảnh) hơn, sẽ đem lại sự đồng cảm cũng như niềm tin hơn l&agrave; cảm thấy một ch&uacute;t &ldquo;nhảm nh&iacute;&rdquo; ở cảnh n&agrave;y.</p>';

        $faker = \Faker\Factory::create();
        $casts_id = Cast::all()->pluck('id')->toArray();
        $movie_genre = MovieGenre::all()->pluck('id')->toArray();
        $format = FormatMovie::all()->pluck('id')->toArray();

        try {
            DB::beginTransaction();
            for ($i = 0; $i < 200; $i++) {
                $movie = Movie::create([
                    'name' => $faker->name,
                    'director' => $faker->name,
                    'description' => $data_description,
                    'trailer' =>  $dataUrlYoutube[array_rand($dataUrlYoutube)],
                    'movie_length' => 120,
                    'rated' => 16,
                    'status' => array_rand([0, 1]),
                ]);
                $movie_id = $movie->id;

                for ($j = 1; $j < 2; $j++) {
                    CastMovie::create([
                        'cast_id' => $casts_id[array_rand($casts_id)],
                        'movie_id' => $movie_id,
                    ]);

                    MovieGenreMovie::create([
                        'movie_genre_id' => $movie_genre[array_rand($movie_genre)],
                        'movie_id' => $movie_id,
                    ]);

                    MovieFormatMovie::create([
                        'format_movie_id' => $format[array_rand($format)],
                        'movie_id' => $movie_id,
                    ]);
                }
            }

            DB::commit();
        } catch (\Exception $e) {
            DB::rollback();
            return dd($e);
        }

        $arr_movie_id = Movie::where('status', Movie::MOVIE_ACTIVE)
            ->limit(10)->get()
            ->pluck('id')->toArray();

        $arr_cinema_id = Cinema::all()->pluck('id')->toArray();

        foreach ($arr_movie_id as $key) {
            foreach ($arr_cinema_id as $item) {
                CinemaMovie::create([
                    'cinema_id' => $item,
                    'movie_id' => $key,
                ]);
            }
        }
    }
}
