export const ROLE_ADMIN = 0
export const ROLE_HOSPITAL = 1
export const ROLE_USER = 2

export const CONTACT_STATUS_UNREAD = 0
export const CONTACT_STATUS_READ = 1

export const HOSPITAL_STATUS_PENDING = 10
export const HOSPITAL_STATUS_DONE = 11
export const HOSPITAL_STATUS_DEACTIVE = 12

export const CARETAKER_STATUS_PENDING = 10
export const CARETAKER_STATUS_DONE = 11
export const CARETAKER_STATUS_DEACTIVE = 12

export const ACCOUNT_STATUS_SUSPEND = 9;
export const ACCOUNT_STATUS_DONE = 11;

export const CONTACT_TYPE_HOSPITAL = 1
export const CONTACT_TYPE_CARETAKER = 2

export const JOB_STATUS_WAITING = 0
export const JOB_STATUS_PUBLIC = 1
export const JOB_STATUS_UPDATING = 2
export const JOB_STATUS_PENDING = 3

export const COMMENT_STATUS_SHOW = 1
export const COMMENT_STATUS_HIDE = 0

export const NOTIFICATION_TYPE_CARETAKER = 'CARETAKER'
export const NOTIFICATION_TYPE_HOSPITAL = 'HOSPITAL'
export const NOTIFICATION_TYPE_ALL = 'ALL'
